services:
    frontend:
        build:
            args:
                NGINX_VERSION: 1.26.2-alpine3.20-slim
                NODE_VERSION: 20.18.1-alpine3.19
            context: .
            dockerfile: Dockerfile
        image: registry.ljournalist.ru/loco/frontend-external-app
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.frontend-staff.rule=Host(`staff.ljournalist.ru`)"
                - "traefik.http.services.frontend-staff.loadBalancer.server.port=8080"
                - "traefik.http.routers.frontend-staff.middlewares=secHeaders@file"
            restart_policy:
                condition: any
        networks:
            - proxy

networks:
    internal:
        external: false
    proxy:
        external: true